import { Button } from '@/components/ui/button'
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { PasswordInput } from '@/components/ui/password-input'
import { Textarea } from '@/components/ui/textarea'
import { useCoreEditorStore } from '@/features/core-editor/state/core-editor-store'
import useDirDetection from '@/hooks/use-dir-detection'
import { cn } from '@/lib/utils'
import { generateWireGuardKeyPair } from '@pasarguard/core-kit/wireguard'
import type { WireGuardCoreDraft, WireGuardCoreFieldKey } from '@pasarguard/wireguard-config-kit'
import { getWireGuardCoreFormCapabilities, syncWireGuardCoreDraftPublicKey } from '@pasarguard/wireguard-config-kit'
import { RefreshCcw } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useForm } from 'react-hook-form'
import { useTranslation } from 'react-i18next'
import { toast } from 'sonner'

function updateDraft(draft: WireGuardCoreDraft, key: keyof WireGuardCoreDraft, value: unknown): WireGuardCoreDraft {
  if (key === 'privateKey') {
    return syncWireGuardCoreDraftPublicKey({ ...draft, privateKey: String(value) })
  }
  return { ...draft, [key]: value } as WireGuardCoreDraft
}

function draftToFormValues(draft: WireGuardCoreDraft, fieldOrder: readonly WireGuardCoreFieldKey[]): Record<string, string> {
  const o: Record<string, string> = {}
  for (const k of fieldOrder) {
    if (k === 'extra') continue
    const v = draft[k as keyof WireGuardCoreDraft]
    o[k] = Array.isArray(v) ? (v as string[]).join('\n') : String(v ?? '')
  }
  return o
}

function wireGuardFieldLabel(key: string, fallback: string, t: (key: string, o?: { defaultValue?: string }) => string): string {
  return t(`coreEditor.wg.fields.${key}`, { defaultValue: fallback })
}

const WIREGUARD_FIELD_ORDER = ['interfaceName', 'listenPort', 'privateKey', 'publicKey', 'preSharedKey', 'address'] as const satisfies readonly WireGuardCoreFieldKey[]

function orderedWireGuardFieldKeys(fieldOrder: readonly WireGuardCoreFieldKey[]): WireGuardCoreFieldKey[] {
  const available = new Set(fieldOrder)
  const preferred = WIREGUARD_FIELD_ORDER.filter(key => available.has(key))
  const rest = fieldOrder.filter(key => key !== 'extra' && !preferred.includes(key))
  return [...preferred, ...rest]
}

function generateWireGuardPreSharedKey(): string {
  const bytes = new Uint8Array(32)
  globalThis.crypto.getRandomValues(bytes)
  let binary = ''
  for (const byte of bytes) binary += String.fromCharCode(byte)
  return btoa(binary)
}

export function WireGuardCoreForm({ className }: { className?: string }) {
  const { t } = useTranslation()
  const dir = useDirDetection()
  const draft = useCoreEditorStore(s => s.wgDraft)
  const isNew = useCoreEditorStore(s => s.isNew)
  const updateWgDraft = useCoreEditorStore(s => s.updateWgDraft)
  const caps = useMemo(() => getWireGuardCoreFormCapabilities(), [])

  const values = useMemo(() => (draft ? draftToFormValues(draft, caps.fieldOrder) : {}), [draft, caps.fieldOrder])

  const form = useForm<Record<string, string>>({ values })
  const formFieldOrder = useMemo(() => orderedWireGuardFieldKeys(caps.fieldOrder), [caps.fieldOrder])

  const [isNameAutoGenerated, setIsNameAutoGenerated] = useState(true)

  const watchedListenPort = form.watch('listenPort')

  useEffect(() => {
    const tagSeparator = ' '
    if (isNew && isNameAutoGenerated && watchedListenPort) {
      const name = `wg${tagSeparator}${watchedListenPort}`.toUpperCase()
      form.setValue('interfaceName', name)
      updateWgDraft(d => ({ ...d, interfaceName: name }))
    }
  }, [isNew, isNameAutoGenerated, watchedListenPort, form, updateWgDraft])

  if (!draft) return null

  const onField = (key: keyof WireGuardCoreDraft, value: unknown) => {
    updateWgDraft(d => updateDraft(d, key, value))
  }

  const regenKeys = () => {
    try {
      const pair = generateWireGuardKeyPair()
      form.setValue('privateKey', pair.privateKey, { shouldDirty: true })
      form.setValue('publicKey', pair.publicKey, { shouldDirty: true })
      updateWgDraft(d => syncWireGuardCoreDraftPublicKey({ ...d, privateKey: pair.privateKey, publicKey: pair.publicKey }))
      toast.success(t('coreEditor.wg.keysRegenerated', { defaultValue: 'New keypair generated' }))
    } catch {
      toast.error(t('coreEditor.wg.keysFailed', { defaultValue: 'Could not generate keys' }))
    }
  }

  const regenPreSharedKey = () => {
    try {
      const key = generateWireGuardPreSharedKey()
      form.setValue('preSharedKey', key, { shouldDirty: true })
      onField('preSharedKey', key)
      toast.success(t('coreEditor.wg.preSharedKeyGenerated', { defaultValue: 'Pre-shared key generated' }))
    } catch {
      toast.error(t('coreEditor.wg.preSharedKeyFailed', { defaultValue: 'Could not generate pre-shared key' }))
    }
  }

  return (
    <Form {...form}>
      <form className={cn(className)} onSubmit={e => e.preventDefault()}>
        <div className="grid grid-cols-1 gap-x-4 gap-y-5 sm:grid-cols-2">
          {formFieldOrder.map(key => {
            const field = caps.fields[key]
            if (!field) return null
            const label = wireGuardFieldLabel(key, field.label, t)
            const fieldClassName = key === 'preSharedKey' || key === 'address' ? 'sm:col-span-2' : undefined
            if (field.input === 'readonly') {
              const isPublicKey = key === 'publicKey'
              return (
                <FormField
                  key={key}
                  control={form.control}
                  name={key}
                  render={({ field: f }) => (
                    <FormItem className={fieldClassName}>
                      <FormLabel>{label}</FormLabel>
                      <FormControl>
                        <Input readOnly={!isPublicKey} disabled={isPublicKey} className="text-xs" dir="ltr" {...f} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              )
            }
            if (field.input === 'secret' || field.input === 'text') {
              if (key === 'publicKey') {
                return (
                  <FormField
                    key={key}
                    control={form.control}
                    name={key}
                    render={({ field: f }) => (
                      <FormItem>
                        <FormLabel>{label}</FormLabel>
                        <FormControl>
                          <Input disabled className="text-xs" dir="ltr" placeholder={field.placeholder} {...f} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                )
              }
              const showKeygen = key === 'privateKey'
              const showPreSharedKeygen = key === 'preSharedKey'
              return (
                <FormField
                  key={key}
                  control={form.control}
                  name={key}
                  render={({ field: f }) => (
                    <FormItem className={fieldClassName}>
                      <FormLabel>{label}</FormLabel>
                      <FormControl>
                        {showKeygen || showPreSharedKeygen ? (
                          <div dir="ltr" className={cn('flex items-center gap-2', dir === 'rtl' ? 'flex-row-reverse' : 'flex-row')}>
                            <div className="min-w-0 flex-1">
                              <PasswordInput
                                placeholder={field.placeholder}
                                className="text-xs"
                                {...f}
                                onChange={e => {
                                  const val = e.target.value
                                  f.onChange(val)
                                  onField(key as keyof WireGuardCoreDraft, val)
                                }}
                              />
                            </div>
                            <Button
                              type="button"
                              size="icon"
                              variant="ghost"
                              className="h-9 w-9 shrink-0"
                              onClick={showPreSharedKeygen ? regenPreSharedKey : regenKeys}
                              title={
                                showPreSharedKeygen
                                  ? t('coreEditor.wg.generatePreSharedKey', { defaultValue: 'Generate pre-shared key' })
                                  : t('coreEditor.wg.regenerateKeys', { defaultValue: 'Regenerate keypair' })
                              }
                            >
                              <RefreshCcw className="h-3 w-3" />
                            </Button>
                          </div>
                        ) : field.input === 'secret' ? (
                          <PasswordInput
                            placeholder={field.placeholder}
                            className="text-xs"
                            dir="ltr"
                            {...f}
                            onChange={e => {
                              const val = e.target.value
                              f.onChange(val)
                              onField(key as keyof WireGuardCoreDraft, val)
                            }}
                          />
                        ) : (
                          <Input
                            type="text"
                            placeholder={field.placeholder}
                            className="text-xs"
                            dir="ltr"
                            {...f}
                            onChange={e => {
                              const val = e.target.value
                              f.onChange(val)
                              if (key === 'interfaceName') {
                                setIsNameAutoGenerated(false)
                              }
                              onField(key as keyof WireGuardCoreDraft, val)
                            }}
                          />
                        )}
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              )
            }
            if (field.input === 'number') {
              const showRandomPort = key === 'listenPort'
              return (
                <FormField
                  key={key}
                  control={form.control}
                  name={key}
                  render={({ field: f }) => (
                    <FormItem className={fieldClassName}>
                      <FormLabel>{label}</FormLabel>
                      <FormControl>
                        {showRandomPort ? (
                          <div dir="ltr" className={cn('flex items-center gap-2', dir === 'rtl' ? 'flex-row-reverse' : 'flex-row')}>
                            <div className="min-w-0 flex-1">
                              <Input
                                type="text"
                                inputMode="numeric"
                                placeholder={field.placeholder}
                                className="text-xs"
                                {...f}
                                onChange={e => {
                                  const val = e.target.value
                                  f.onChange(val)
                                  onField(key as keyof WireGuardCoreDraft, val)
                                }}
                              />
                            </div>
                            <Button
                              type="button"
                              size="icon"
                              variant="ghost"
                              className="h-9 w-9 shrink-0"
                              onClick={() => {
                                const p = Math.floor(Math.random() * (65535 - 10000 + 1)) + 10000
                                f.onChange(String(p))
                                onField(key as keyof WireGuardCoreDraft, String(p))
                              }}
                              title={t('coreEditor.inbound.randomPort', { defaultValue: 'Generate random port' })}
                            >
                              <RefreshCcw className="h-3 w-3" />
                            </Button>
                          </div>
                        ) : (
                          <Input
                            type="text"
                            inputMode="numeric"
                            placeholder={field.placeholder}
                            className="text-xs"
                            {...f}
                            onChange={e => {
                              const val = e.target.value
                              f.onChange(val)
                              onField(key as keyof WireGuardCoreDraft, val)
                            }}
                          />
                        )}
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              )
            }
            if (field.input === 'string-array') {
              return (
                <FormField
                  key={key}
                  control={form.control}
                  name={key}
                  render={({ field: f }) => (
                    <FormItem className="sm:col-span-2">
                      <FormLabel>{label}</FormLabel>
                      <FormControl>
                        <Textarea
                          rows={4}
                          className="text-xs"
                          dir="ltr"
                          placeholder={field.placeholder}
                          {...f}
                          onChange={e => {
                            const val = e.target.value
                            f.onChange(val)
                            onField(
                              key as keyof WireGuardCoreDraft,
                              val
                                .split('\n')
                                .map(s => s.trim())
                                .filter(Boolean),
                            )
                          }}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              )
            }
            return null
          })}
          <FormItem className="sm:col-span-2">
            <FormLabel>{wireGuardFieldLabel('egressInterface', 'Egress interface (optional)', t)}</FormLabel>
            <FormControl>
              <Input
                dir="ltr"
                className="text-xs"
                placeholder="wg-de"
                value={String((draft.extra?.egress_interface as string) ?? '')}
                onChange={e => {
                  const val = e.target.value
                  updateWgDraft(d => {
                    const extra = { ...(d.extra ?? {}) }
                    if (val.trim()) extra.egress_interface = val.trim()
                    else delete extra.egress_interface
                    return { ...d, extra }
                  })
                }}
              />
            </FormControl>
            <p className="text-muted-foreground text-[11px]">
              {t('coreEditor.wg.egressHint', {
                defaultValue: "Route this core's traffic out a specific interface on the node (e.g. an upstream tunnel). Leave empty for the default route.",
              })}
            </p>
          </FormItem>

          <AmneziaSection draft={draft} updateWgDraft={updateWgDraft} t={t} />
        </div>
      </form>
    </Form>
  )
}

// Plain WireGuard has a fixed handshake size and fixed header bytes, so DPI can
// block it with a single rule. These settings pad and randomise those. They are
// written into the client's .conf too, and a peer whose numbers differ from the
// server's never completes a handshake — hence the "must match" warning and the
// one-click preset rather than nine free-form numbers.
const AMNEZIA_FIELDS = [
  { key: 'jc', label: 'Jc', hint: 'Junk packets before the handshake' },
  { key: 'jmin', label: 'Jmin', hint: 'Smallest junk packet (bytes)' },
  { key: 'jmax', label: 'Jmax', hint: 'Largest junk packet (bytes)' },
  { key: 's1', label: 'S1', hint: 'Init packet padding' },
  { key: 's2', label: 'S2', hint: 'Response packet padding' },
  { key: 'h1', label: 'H1', hint: 'Init header (≥5)' },
  { key: 'h2', label: 'H2', hint: 'Response header (≥5)' },
  { key: 'h3', label: 'H3', hint: 'Cookie header (≥5)' },
  { key: 'h4', label: 'H4', hint: 'Transport header (≥5)' },
] as const

function randomAmneziaPreset(): Record<string, number> {
  // Headers must be ≥5 (1-4 are the real WireGuard message types) and all
  // distinct; randomising them per core is the point — a shared constant would
  // just become the next fingerprint.
  const headers = new Set<number>()
  while (headers.size < 4) headers.add(Math.floor(Math.random() * 0x7ffffff) + 5)
  const [h1, h2, h3, h4] = [...headers]
  const jmin = 8 + Math.floor(Math.random() * 20)
  const s1 = 15 + Math.floor(Math.random() * 40)
  let s2 = 15 + Math.floor(Math.random() * 40)
  // s1 + 56 === s2 would make two different message types the same size.
  if (s1 + 56 === s2) s2 += 1
  return {
    jc: 3 + Math.floor(Math.random() * 5),
    jmin,
    jmax: jmin + 30 + Math.floor(Math.random() * 40),
    s1,
    s2,
    h1,
    h2,
    h3,
    h4,
  }
}

function AmneziaSection({
  draft,
  updateWgDraft,
  t,
}: {
  draft: any
  updateWgDraft: (fn: (d: any) => any) => void
  t: any
}) {
  const amnezia = (draft.extra?.amnezia ?? {}) as Record<string, number | undefined>
  const enabled = AMNEZIA_FIELDS.some(f => Number(amnezia[f.key]) > 0)

  const setAmnezia = (next: Record<string, number> | null) =>
    updateWgDraft(d => {
      const extra = { ...(d.extra ?? {}) }
      if (next) extra.amnezia = next
      else delete extra.amnezia
      return { ...d, extra }
    })

  return (
    <div className="sm:col-span-2 rounded-md border p-3 space-y-3">
      <div className="flex items-center justify-between gap-2 flex-wrap">
        <div>
          <p className="text-sm font-medium">
            {t('coreEditor.wg.amnezia', { defaultValue: 'AmneziaWG obfuscation (optional)' })}
          </p>
          <p className="text-muted-foreground text-[11px]">
            {t('coreEditor.wg.amneziaHint', {
              defaultValue:
                'Hides the WireGuard signature from DPI. Clients must use an Amnezia-compatible app, and the values below are written into their config — they must match exactly.',
            })}
          </p>
        </div>
        <div className="flex gap-2">
          <button
            type="button"
            className="rounded-md border px-2 py-1 text-xs"
            onClick={() => setAmnezia(randomAmneziaPreset())}
          >
            {t('coreEditor.wg.amneziaGenerate', { defaultValue: 'Generate' })}
          </button>
          {enabled && (
            <button type="button" className="rounded-md border px-2 py-1 text-xs" onClick={() => setAmnezia(null)}>
              {t('coreEditor.wg.amneziaClear', { defaultValue: 'Disable' })}
            </button>
          )}
        </div>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
        {AMNEZIA_FIELDS.map(field => (
          <FormItem key={field.key}>
            <FormLabel className="text-xs">{field.label}</FormLabel>
            <FormControl>
              <Input
                dir="ltr"
                type="number"
                min={0}
                className="text-xs"
                value={amnezia[field.key] ?? ''}
                onChange={e => {
                  const raw = e.target.value.trim()
                  const next = { ...amnezia } as Record<string, number>
                  if (raw === '') delete next[field.key]
                  else next[field.key] = Number(raw)
                  setAmnezia(Object.keys(next).length ? next : null)
                }}
              />
            </FormControl>
            <p className="text-muted-foreground text-[10px]">{field.hint}</p>
          </FormItem>
        ))}
      </div>
    </div>
  )
}
