export const REPO_URL = 'https://klaris-sub.top'
export const ORGANIZATION_URL = 'https://klaris-sub.top'
export const DONATION_URL = 'https://klaris-sub.top'
export const DISCUSSION_GROUP = 'https://klaris-sub.top'
export const DOCUMENTATION = 'https://klaris-sub.top'
