# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common import service_pb2 as common_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in common/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub:
    """Service for node management and connection
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/service.NodeService/Start',
                request_serializer=common_dot_service__pb2.Backend.SerializeToString,
                response_deserializer=common_dot_service__pb2.BaseInfoResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/service.NodeService/Stop',
                request_serializer=common_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=common_dot_service__pb2.Empty.FromString,
                _registered_method=True)
        self.GetBaseInfo = channel.unary_unary(
                '/service.NodeService/GetBaseInfo',
                request_serializer=common_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=common_dot_service__pb2.BaseInfoResponse.FromString,
                _registered_method=True)
        self.GetLogs = channel.unary_stream(
                '/service.NodeService/GetLogs',
                request_serializer=common_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=common_dot_service__pb2.Log.FromString,
                _registered_method=True)
        self.GetSystemStats = channel.unary_unary(
                '/service.NodeService/GetSystemStats',
                request_serializer=common_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=common_dot_service__pb2.SystemStatsResponse.FromString,
                _registered_method=True)
        self.GetBackendStats = channel.unary_unary(
                '/service.NodeService/GetBackendStats',
                request_serializer=common_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=common_dot_service__pb2.BackendStatsResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/service.NodeService/GetStats',
                request_serializer=common_dot_service__pb2.StatRequest.SerializeToString,
                response_deserializer=common_dot_service__pb2.StatResponse.FromString,
                _registered_method=True)
        self.GetOutboundsLatency = channel.unary_unary(
                '/service.NodeService/GetOutboundsLatency',
                request_serializer=common_dot_service__pb2.LatencyRequest.SerializeToString,
                response_deserializer=common_dot_service__pb2.LatencyResponse.FromString,
                _registered_method=True)
        self.GetUserOnlineStats = channel.unary_unary(
                '/service.NodeService/GetUserOnlineStats',
                request_serializer=common_dot_service__pb2.StatRequest.SerializeToString,
                response_deserializer=common_dot_service__pb2.OnlineStatResponse.FromString,
                _registered_method=True)
        self.GetUserOnlineIpListStats = channel.unary_unary(
                '/service.NodeService/GetUserOnlineIpListStats',
                request_serializer=common_dot_service__pb2.StatRequest.SerializeToString,
                response_deserializer=common_dot_service__pb2.StatsOnlineIpListResponse.FromString,
                _registered_method=True)
        self.SyncUser = channel.stream_unary(
                '/service.NodeService/SyncUser',
                request_serializer=common_dot_service__pb2.User.SerializeToString,
                response_deserializer=common_dot_service__pb2.Empty.FromString,
                _registered_method=True)
        self.SyncUsers = channel.unary_unary(
                '/service.NodeService/SyncUsers',
                request_serializer=common_dot_service__pb2.Users.SerializeToString,
                response_deserializer=common_dot_service__pb2.Empty.FromString,
                _registered_method=True)
        self.SyncUsersChunked = channel.stream_unary(
                '/service.NodeService/SyncUsersChunked',
                request_serializer=common_dot_service__pb2.UsersChunk.SerializeToString,
                response_deserializer=common_dot_service__pb2.Empty.FromString,
                _registered_method=True)


class NodeServiceServicer:
    """Service for node management and connection
    """

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBaseInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBackendStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOutboundsLatency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserOnlineStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserOnlineIpListStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncUser(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncUsersChunked(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=common_dot_service__pb2.Backend.FromString,
                    response_serializer=common_dot_service__pb2.BaseInfoResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=common_dot_service__pb2.Empty.FromString,
                    response_serializer=common_dot_service__pb2.Empty.SerializeToString,
            ),
            'GetBaseInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBaseInfo,
                    request_deserializer=common_dot_service__pb2.Empty.FromString,
                    response_serializer=common_dot_service__pb2.BaseInfoResponse.SerializeToString,
            ),
            'GetLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.GetLogs,
                    request_deserializer=common_dot_service__pb2.Empty.FromString,
                    response_serializer=common_dot_service__pb2.Log.SerializeToString,
            ),
            'GetSystemStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStats,
                    request_deserializer=common_dot_service__pb2.Empty.FromString,
                    response_serializer=common_dot_service__pb2.SystemStatsResponse.SerializeToString,
            ),
            'GetBackendStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBackendStats,
                    request_deserializer=common_dot_service__pb2.Empty.FromString,
                    response_serializer=common_dot_service__pb2.BackendStatsResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=common_dot_service__pb2.StatRequest.FromString,
                    response_serializer=common_dot_service__pb2.StatResponse.SerializeToString,
            ),
            'GetOutboundsLatency': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOutboundsLatency,
                    request_deserializer=common_dot_service__pb2.LatencyRequest.FromString,
                    response_serializer=common_dot_service__pb2.LatencyResponse.SerializeToString,
            ),
            'GetUserOnlineStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserOnlineStats,
                    request_deserializer=common_dot_service__pb2.StatRequest.FromString,
                    response_serializer=common_dot_service__pb2.OnlineStatResponse.SerializeToString,
            ),
            'GetUserOnlineIpListStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserOnlineIpListStats,
                    request_deserializer=common_dot_service__pb2.StatRequest.FromString,
                    response_serializer=common_dot_service__pb2.StatsOnlineIpListResponse.SerializeToString,
            ),
            'SyncUser': grpc.stream_unary_rpc_method_handler(
                    servicer.SyncUser,
                    request_deserializer=common_dot_service__pb2.User.FromString,
                    response_serializer=common_dot_service__pb2.Empty.SerializeToString,
            ),
            'SyncUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncUsers,
                    request_deserializer=common_dot_service__pb2.Users.FromString,
                    response_serializer=common_dot_service__pb2.Empty.SerializeToString,
            ),
            'SyncUsersChunked': grpc.stream_unary_rpc_method_handler(
                    servicer.SyncUsersChunked,
                    request_deserializer=common_dot_service__pb2.UsersChunk.FromString,
                    response_serializer=common_dot_service__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('service.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService:
    """Service for node management and connection
    """

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.NodeService/Start',
            common_dot_service__pb2.Backend.SerializeToString,
            common_dot_service__pb2.BaseInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.NodeService/Stop',
            common_dot_service__pb2.Empty.SerializeToString,
            common_dot_service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBaseInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.NodeService/GetBaseInfo',
            common_dot_service__pb2.Empty.SerializeToString,
            common_dot_service__pb2.BaseInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/service.NodeService/GetLogs',
            common_dot_service__pb2.Empty.SerializeToString,
            common_dot_service__pb2.Log.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.NodeService/GetSystemStats',
            common_dot_service__pb2.Empty.SerializeToString,
            common_dot_service__pb2.SystemStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBackendStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.NodeService/GetBackendStats',
            common_dot_service__pb2.Empty.SerializeToString,
            common_dot_service__pb2.BackendStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.NodeService/GetStats',
            common_dot_service__pb2.StatRequest.SerializeToString,
            common_dot_service__pb2.StatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOutboundsLatency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.NodeService/GetOutboundsLatency',
            common_dot_service__pb2.LatencyRequest.SerializeToString,
            common_dot_service__pb2.LatencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserOnlineStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.NodeService/GetUserOnlineStats',
            common_dot_service__pb2.StatRequest.SerializeToString,
            common_dot_service__pb2.OnlineStatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserOnlineIpListStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.NodeService/GetUserOnlineIpListStats',
            common_dot_service__pb2.StatRequest.SerializeToString,
            common_dot_service__pb2.StatsOnlineIpListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncUser(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/service.NodeService/SyncUser',
            common_dot_service__pb2.User.SerializeToString,
            common_dot_service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.NodeService/SyncUsers',
            common_dot_service__pb2.Users.SerializeToString,
            common_dot_service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncUsersChunked(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/service.NodeService/SyncUsersChunked',
            common_dot_service__pb2.UsersChunk.SerializeToString,
            common_dot_service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
